dev.langchain4j.cdi.plugin.chat-model.class=dev.langchain4j.model.openai.OpenAiChatModel
dev.langchain4j.cdi.plugin.chat-model.config.api-key=<<OPENAI_API_KEY>>
dev.langchain4j.cdi.plugin.chat-model.config.model-name=gpt-5

openai.api-key=<<OPENAI_API_KEY>>
mongodb.connection-string=<<MONGODB_CONNECTION_STRING>>
mongodb.database=langchain
mongodb.collection=documents
openai.embedding.model=text-embedding-3-small